no need to wipe a gpg file, fixed removal error tests --chongo

diff --git a/gdecrypt b/gdecrypt
--- a/gdecrypt
+++ b/gdecrypt
@@ -2,9 +2,9 @@
 #
 # gdecrypt - gpg decrypt a file
 #
-# @(#) $Revision$
-# @(#) $Id$
-# @(#) $Source$
+# @(#) $Revision: 1.1 $
+# @(#) $Id: gdecrypt,v 1.1 2006/02/25 19:11:14 chongo Exp chongo $
+# @(#) $Source: /usr/local/src/cmd/gencrypt/RCS/gdecrypt,v $
 #
 # Copyright (c) 2006 by Landon Curt Noll.  All Rights Reserved.
 #
@@ -123,19 +123,18 @@ while [[ $# -gt 0 ]]; do
 	continue
     fi
 
-    # securely remove the old file
+    # remove the gpgfile we no longer need
     #
-    echo "wiping old $dir/$gpgbase"
-    (cd "$dir"; wipe -v "$gpgbase")
-    status="$?"
-    if [[ $status -ne 0 ]]; then
-	echo "$0: $arg: wipe error code: $status" 1>&2
+    echo "removing old $dir/$gpgbase"
+    rm -f "$dir/$gpgbase"
+    if [[ -e "$dir/$gpgbase" ]]; then
+	echo "$0: $arg: cannot remove old: $gpgbase" 1>&2
 	CODE=12
 	continue
     fi
-    if [[ -f "$gpgfile" ]]; then
+    if [[ -f "$dir/$gpgfile" ]]; then
 	echo "$0: $arg: wipe did not remove file" 1>&2
-	CODE=13
+	CODE=14
 	continue
     fi
 done
diff --git a/gencrypt b/gencrypt
--- a/gencrypt
+++ b/gencrypt
@@ -2,9 +2,9 @@
 #
 # gencrypt - gpg encrypt files
 #
-# @(#) $Revision$
-# @(#) $Id$
-# @(#) $Source$
+# @(#) $Revision: 1.1 $
+# @(#) $Id: gencrypt,v 1.1 2006/02/25 19:11:14 chongo Exp chongo $
+# @(#) $Source: /usr/local/src/cmd/gencrypt/RCS/gencrypt,v $
 #
 # Copyright (c) 2006 by Landon Curt Noll.  All Rights Reserved.
 #
@@ -121,6 +121,14 @@ while [[ $# -gt 0 ]]; do
     # securely remove the old file
     #
     echo "wiping old $dir/$basefile"
+    if [[ ! -w "$dir/$basefile" ]]; then
+	chmod +w "$dir/$basefile" > /dev/null 2>&1
+    fi
+    if [[ ! -w "$dir/$basefile" ]]; then
+	echo "$0: $arg: cannot make writable: $basefile" 1>&2
+	CODE=12
+	continue
+    fi
     (cd "$dir"; wipe -v "$basefile")
     status="$?"
     if [[ $status -ne 0 ]]; then
@@ -128,7 +136,7 @@ while [[ $# -gt 0 ]]; do
 	CODE=11
 	continue
     fi
-    if [[ -f "$file" ]]; then
+    if [[ -f "$dir/$basefile" ]]; then
 	echo "$0: $arg: wipe did not remove file: $dir/$basefile" 1>&2
 	CODE=12
 	continue
